lis = [
    ################################# cdca #################################
    "Access to Justice", 
    "Animal Welfare", 
    "Antitrust", 
    "Asset Forfeiture", 
    "Bankruptcy", 
    "Civil Rights", 
    "Civil Rights", 
    "Community Outreach", 
    "Consumer Protection", 
    "Coronavirus", 
    "Countering Nation-State Threats", 
    "Counterintelligence", 
    "Counterterrorism", 
    "Cybercrime", 
    "Disability Rights", 
    "Disaster Fraud", 
    "Domestic Terrorism", 
    "Drugs", 
    "Drug Trafficking", 
    "Elder Justice", 
    "Environment", 
    "Environment", 
    "Environmental Justice", 
    "Export Control", 
    "Fair Housing", 
    "False Claims Act", 
    "Financial Fraud", 
    "Firearms Offenses", 
    "Grants", 
    "Hate Crimes", 
    "Health Care Fraud", 
    "Human Smuggling", 
    "Human Trafficking", 
    "Identity Theft", 
    "Immigration", 
    "Immigration", 
    "Indian Country Law and Justice", 
    "Initiatives and Projects", 
    "Intellectual Property", 
    "Labor & Employment", 
    "Mortgage Fraud", 
    "National Security", 
    "National Security", 
    "Office and Personnel Updates", 
    "Opioids", 
    "Prescription Drugs", 
    "Project Safe Childhood", 
    "Project Safe Neighborhoods", 
    "Public Corruption", 
    "Securities, Commodities, & Investment Fraud", 
    "Servicemembers Initiative", 
    "Tax", 
    "Violent Crime", 
    "Voting and Elections", 
    "Wildlife", 

    ################################# d dc #################################
    "Animal Welfare", 
    "Antitrust", 
    "Asset Forfeiture", 
    "Civil Rights", 
    "Civil Rights", 
    "Community Outreach", 
    "Consumer Protection", 
    "Coronavirus", 
    "Countering Nation-State Threats", 
    "Counterintelligence", 
    "Counterterrorism", 
    "Cybercrime", 
    "Disaster Fraud", 
    "Drugs", 
    "Drug Trafficking", 
    "Elder Justice", 
    "Environment", 
    "Environment", 
    "Environmental Justice", 
    "Export Control", 
    "False Claims Act", 
    "Financial Fraud", 
    "Firearms Offenses", 
    "Grants", 
    "Hate Crimes", 
    "Health Care Fraud", 
    "Human Smuggling", 
    "Human Trafficking", 
    "Identity Theft", 
    "Immigration", 
    "Immigration", 
    "Initiatives and Projects", 
    "Intellectual Property", 
    "Labor & Employment", 
    "Mortgage Fraud", 
    "National Security", 
    "National Security", 
    "Office and Personnel Updates", 
    "Opioids", 
    "Prescription Drugs", 
    "Project Safe Childhood", 
    "Project Safe Neighborhoods", 
    "Public Corruption", 
    "Securities, Commodities, & Investment Fraud", 
    "Tax", 
    "Violent Crime", 
    "Voting and Elections", 

    ################################# SDNY #################################
    "Animal Welfare", 
    "Asset Forfeiture", 
    "Bankruptcy", 
    "Civil Rights", 
    "Civil Rights", 
    "Community Outreach", 
    "Consumer Protection", 
    "Coronavirus", 
    "Counterintelligence", 
    "Counterterrorism", 
    "Cybercrime", 
    "Disaster Fraud", 
    "Domestic Terrorism", 
    "Drugs", 
    "Drug Trafficking", 
    "Elder Justice", 
    "Environment", 
    "Environment", 
    "Environmental Justice", 
    "Export Control", 
    "False Claims Act", 
    "Financial Fraud", 
    "Firearms Offenses", 
    "Foreign Corruption", 
    "Hate Crimes", 
    "Health Care Fraud", 
    "Human Smuggling", 
    "Human Trafficking", 
    "Identity Theft", 
    "Immigration", 
    "Immigration", 
    "Initiatives and Projects", 
    "Intellectual Property", 
    "Labor & Employment", 
    "Mortgage Fraud", 
    "National Security", 
    "National Security", 
    "Office and Personnel Updates", 
    "Opioids", 
    "Prescription Drugs", 
    "Project Safe Childhood", 
    "Project Safe Neighborhoods", 
    "Public Corruption", 
    "Securities, Commodities, & Investment Fraud", 
    "StopFraud", 
    "Tax", 
    "Violent Crime", 
    "Voting and Elections", 
    "Wildlife", 

    ################################# EDNY #################################
    "Access to Justice", 
    "Animal Welfare", 
    "Asset Forfeiture", 
    "Civil Rights", 
    "Civil Rights", 
    "Community Outreach", 
    "Consumer Protection", 
    "Coronavirus", 
    "Countering Nation-State Threats", 
    "Counterintelligence", 
    "Counterterrorism", 
    "Cybercrime", 
    "Disability Rights", 
    "Disaster Fraud", 
    "Domestic Terrorism", 
    "Drugs", 
    "Drug Trafficking", 
    "Elder Justice", 
    "Environment", 
    "Environment", 
    "Environmental Justice", 
    "Export Control", 
    "False Claims Act", 
    "Financial Fraud", 
    "Firearms Offenses", 
    "Foreign Corruption", 
    "Grants", 
    "Hate Crimes", 
    "Health Care Fraud", 
    "Human Smuggling", 
    "Human Trafficking", 
    "Identity Theft", 
    "Immigration", 
    "Immigration", 
    "Initiatives and Projects", 
    "Intellectual Property", 
    "Labor & Employment", 
    "Mortgage Fraud", 
    "National Security", 
    "National Security", 
    "Office and Personnel Updates", 
    "Opioids", 
    "Prescription Drugs", 
    "Project Guardian", 
    "Project Safe Childhood", 
    "Project Safe Neighborhoods", 
    "Public Corruption", 
    "Securities, Commodities, & Investment Fraud", 
    "Servicemembers Initiative", 
    "StopFraud", 
    "Tax", 
    "Violent Crime", 
    "Voting and Elections", 
    "Wildlife", 

    ################################# ND Ill #################################
    "Antitrust", 
    "Asset Forfeiture", 
    "Bankruptcy", 
    "Civil Rights", 
    "Civil Rights", 
    "Community Outreach", 
    "Consumer Protection", 
    "Coronavirus", 
    "Countering Nation-State Threats", 
    "Counterintelligence", 
    "Counterterrorism", 
    "Cybercrime", 
    "Disability Rights", 
    "Disaster Fraud", 
    "Domestic Terrorism", 
    "Drugs", 
    "Drug Trafficking", 
    "Elder Justice", 
    "Environment", 
    "Environment", 
    "Environmental Justice", 
    "Export Control", 
    "Fair Housing", 
    "False Claims Act", 
    "Financial Fraud", 
    "Firearms Offenses", 
    "Foreign Corruption", 
    "Grants", 
    "Hate Crimes", 
    "Health Care Fraud", 
    "Human Smuggling", 
    "Human Trafficking", 
    "Identity Theft", 
    "Immigration", 
    "Immigration", 
    "Initiatives and Projects", 
    "Intellectual Property", 
    "Labor & Employment", 
    "Mortgage Fraud", 
    "National Security", 
    "National Security", 
    "Office and Personnel Updates", 
    "Operation Legend", 
    "Opioids", 
    "Prescription Drugs", 
    "Project Guardian", 
    "Project Safe Childhood", 
    "Project Safe Neighborhoods", 
    "Public Corruption", 
    "Securities, Commodities, & Investment Fraud", 
    "Servicemembers Initiative", 
    "StopFraud", 
    "Tax", 
    "Violent Crime", 
    "Voting and Elections", 
    #################################  #################################
]